### ISSUE TITLE
Upgrade the code examples to function as intended.

### ISSUE THREAD

**Issue by janckerchen** [deno-plc/vite-plugin-deno#3]
两个例子都无法如预期工作

```
> git clone git@github.com:deno-plc/vite-plugin-deno.git

> cd vite-plugin-deno/examples/plain/
> deno run release
Task release deno run -A scripts/release.ts
vite v5.4.9 building for production...
✓ 3 modules transformed.
dist/index.html                0.33 kB │ gzip: 0.23 kB
dist/assets/index-B92LRWDZ.js  0.74 kB │ gzip: 0.42 kB
✓ built in 627ms

(卡在这里无法退出， 需要 ctrl-c 结束)

> cd vite-plugin-deno/examples/preact/
> deno run release

Task release deno run -A scripts/release.ts
vite v5.4.9 building for production...
transforming (4) src/index.csserror: Uncaught (in promise) TypeError: Cannot read properties of null (reading 'exports')
    at Module.o (file:///opt/opensource/js/vite-plugin-deno/examples/preact/node_modules/.deno/resolve.exports@2.0.2/node_modules/resolve.exports/dist/index.mjs:1:1553)
    at NPMPackage.resolve_import (file:///opt/opensource/js/vite-plugin-deno/src/npm.ts:124:38)
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async ModuleGraph.get_module (file:///opt/opensource/js/vite-plugin-deno/src/graph.ts:374:34)
    at async ModuleGraph.get_module (file:///opt/opensource/js/vite-plugin-deno/src/graph.ts:367:20)
    at async ModuleGraph.get_module (file:///opt/opensource/js/vite-plugin-deno/src/graph.ts:360:20)

> deno -v
deno 2.0.6
```

**Comment by hansSchall** [comment]
The first problem is caused by Vite, most likely it does not terminate esbuild correctly (this causes the event loop to hang infinitely). I have added a manual `Deno.exit(0)` to the examples.

I am unable to reproduce the second one on windows, but I will try again on *nix

**Comment by janckerchen** [comment]
First `examples/plain` have been fixed. 

Second `examples/preact` still stuck

```
> cd ../preact/
> deno run release
Task release deno run -A scripts/release.ts
vite v5.4.9 building for production...
transforming (1) index.htmlerror: Uncaught (in promise) TypeError: Cannot read properties of null (reading 'exports')
    at Module.o (file:///opt/opensource/js/vite-plugin-deno/examples/preact/node_modules/.deno/resolve.exports@2.0.2/node_modules/resolve.exports/dist/index.mjs:1:1553)
    at NPMPackage.resolve_import (file:///opt/opensource/js/vite-plugin-deno/src/npm.ts:124:38)
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async ModuleGraph.get_module (file:///opt/opensource/js/vite-plugin-deno/src/graph.ts:374:34)
    at async ModuleGraph.get_module (file:///opt/opensource/js/vite-plugin-deno/src/graph.ts:367:20)
    at async ModuleGraph.get_module (file:///opt/opensource/js/vite-plugin-deno/src/graph.ts:360:20)

> deno --version
deno 2.0.6 (stable, release, aarch64-apple-darwin)
v8 12.9.202.13-rusty
typescript 5.6.2

> sw_vers && system_profiler SPHardwareDataType && xcode-select --version

macOS Version: 15.0 (Build 24A335)
Model Name: MacBook Pro
Model Identifier: MacBookPro17,1
Model Number: Z11B000BZCH/A
Chip: Apple M1
Total Number of Cores: 8 (4 performance and 4 efficiency)
Memory: 16 GB
System Firmware Version: 11881.1.1
OS Loader Version: 11881.1.1
Serial Number (system): C02GJ03AQ05N
Hardware UUID: 93D8EABE-03BA-5853-B432-8AD4459DF3AA
Provisioning UDID: 00008103-000E01321E20801E
Activation Lock Status: Enabled
Xcode Command Line Tools Version: 2409

```
